preset: symfony

finder:
    exclude:
        - "spec"
        - "tests"
    path:
        - "src"

enabled:
    - short_array_syntax

disabled:
    - phpdoc_order # Preferred order: params, return, throws
